### ISSUE TITLE
Plugin request for Buf Schema Registry

### ISSUE THREAD

**Issue by mylegfeelsfunny** [bufbuild/plugins#561]
This plugin is extremely helpful with go services. 

## Mandatory

https://github.com/favadi/protoc-go-inject-tag

## Optional

**Does the plugin have a valid semver version?**

[v1.4.0](https://github.com/favadi/protoc-go-inject-tag/releases/tag/v1.4.0) - From github

**Does the plugin have a dependency on another plugin?**

nope

**Does the output of this plugin depend on any other external libraries?**

nope

**Comment by mfridman** [comment]
Hey @mylegfeelsfunny, thanks for opening up an issue. I can certainly see how this plugin would be useful, especially given the limitations of the base Go plugins and the want to modify the generated code.

However, this plugin will not work as a **Remote Plugin** executed on the BSR because it relies on accessing files from the local filesystem.

All Remote Plugins we add to this repository, and that are available on https://buf.build/plugins satisfy the code generation contract: 

https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/compiler/plugin.proto#L65-L66

Hope this helps, let me know if you have any other issues.
